[package]
name = "ejdb2-sys"
version = "0.1.0"
authors = ["Joylei <leingliu@gmail.com>"]
edition = "2018"

[build-dependencies]
pkg-config = "0.3"
cmake = "0.1"
bindgen = "*"
anyhow = "*"

[dependencies]
libc = "0.2"
